apiVersion: v1
kind: ConfigMap
metadata:
  name: aqua-scanner-config
  namespace: aqua
data:  
  # Aqua Scanner IP/Domain/Servicename followed by HTTPS port.
  AQUA_SERVER: ""

  # Scanner's private key for HTTPS and Mutual Auth with offline CyberCenter
  #AQUA_PRIVATE_KEY: "/opt/aquasec/ssl/key.pem"

  # Scanner's public key for HTTPS and Mutual Auth with offline CyberCenter
  #AQUA_PUBLIC_KEY: "/opt/aquasec/ssl/cert.pem"

  # Scanner's root CA cert for HTTPS and Mutual Auth. The root CA certificate file should be mutual for both CyberCenter and Scanner certificates
  #AQUA_ROOT_CA: "/opt/aquasec/ssl/ca.pem"

  # Set this to 1 to establish mTLS connection with CyberCenter
  #OFFLINE_CC_MTLS_ENABLE: "1"

  # Optional environment variable, to set the max amount of consecutive attempts before back off. There will be a random interval between connection attempts. 
  # (This and AQUA_CONNECTIVITY_BACKOFF_DURATION should both be set to trigger the backoff mechanism)
  #AQUA_MAX_CONSECUTIVE_CONNECTION_ATTEMPTS: "5"

  # Optional environment variable, to set the amount of time (in seconds) in which there is no attempt to connect. 
  # Once this duration passes, the reconnect mechanisim will be triggered again till max attempts.
  #AQUA_CONNECTIVITY_BACKOFF_DURATION: "120"
